### ISSUE TITLE
Depth map

### ISSUE THREAD

**Issue by WangLiwen1994** [majedelhelou/VIDIT#7]
Hello, Thank you for sharing the dataset.

When I tried to visualize some depth maps, I met with the wrap-around problem in some scenes. A case (scene: 290) is shown below:

![img_png](https://user-images.githubusercontent.com/35027128/123058330-4aeae880-d43b-11eb-868a-1da67cd9d44b.png)

I used the following code to load the depth map:

`
    depth_map =  np.load(depth_file, allow_pickle=True).item().get('normalized_depth')
`

and visualized it directly through the OpenCV package:
`
    cv2.imshow("depth map", depth_map )
`

Some value at the warp-around region:
   location: (512,340), normalized depth: 0.07343
   location: (512,341), normalized depth: 0.02910. (The depth should not be suddenly decreased so much, as compared to location (512,342)'s.)
   location: (512,342), normalized depth: 0.98779
   location: (512,343), normalized depth: 0.93311

Another case (scene 223):
![image](https://user-images.githubusercontent.com/35027128/123062841-7a9bef80-d43f-11eb-8b4f-f10b8033ece7.png)

Is there something I did wrong, or is it a problem with the data?

Thank you!

**Comment by majedelhelou** [comment]
Hello
Thank you for your comment. You are not doing anything wrong with the data loading. The wrap-around can come in some rare cases from the rendering in UE, translucent objects/ray tracing (they occur typically at far locations when rendering some scenes). In our workshops, they did not affect the results of different methods because the relighting is already challenging even at shallow depths, so these rare deep regions had negligible effect.
Hope this helps!

**Comment by WangLiwen1994** [comment]
Yes, it only appears in a few scenarios that can be omitted for the challenging task. Thank you for your reply. It resolves my doubt.
